import type { Challenge } from '@/types';

const MOCK_CHALLENGES: Challenge[] = [
  {
    id: 'c1',
    hostName: 'SnipeKing99',
    hostId: 'p1',
    matchType: 'Classic',
    mode: 'Squad',
    map: 'Erangel',
    entryFee: 50,
    prizePool: 400,
    totalSlots: 8,
    filledSlots: 5,
    matchTime: 'Today, 8:00 PM',
    status: 'open',
    rules: 'No teaming. Report results with screenshot within 10 mins of match end.',
    roomId: 'ER12345',
    roomPassword: 'pass99',
  },
  {
    id: 'c2',
    hostName: 'BlazeFire',
    hostId: 'p2',
    matchType: 'TDM',
    mode: 'Duo',
    gunCategory: 'AR',
    gun: 'M416',
    entryFee: 30,
    prizePool: 240,
    totalSlots: 8,
    filledSlots: 8,
    matchTime: 'Today, 9:30 PM',
    status: 'full',
    rules: 'Only M416 allowed. Screenshots mandatory.',
    roomId: 'TD56789',
    roomPassword: 'blaze1',
  },
  {
    id: 'c3',
    hostName: 'ProGamer_X',
    hostId: 'p3',
    matchType: 'WOW',
    mode: 'Solo',
    wowCode: 'WOW-2v2-XZ99',
    entryFee: 20,
    prizePool: 120,
    totalSlots: 6,
    filledSlots: 2,
    matchTime: 'Tomorrow, 7:00 PM',
    status: 'open',
    rules: 'Custom WOW map. Enter code in-game.',
    roomId: 'WW00321',
    roomPassword: 'wow99',
  },
  {
    id: 'c4',
    hostName: 'StealthNinja',
    hostId: 'p4',
    matchType: 'Classic',
    mode: 'Solo',
    map: 'Miramar',
    entryFee: 100,
    prizePool: 600,
    totalSlots: 6,
    filledSlots: 4,
    matchTime: 'Tomorrow, 10:00 PM',
    status: 'open',
    rules: 'Miramar desert rules. No camping inside buildings for > 5 mins.',
    roomId: 'MR99111',
    roomPassword: 'ninja7',
  },
  {
    id: 'c5',
    hostName: 'TurboAce',
    hostId: 'p5',
    matchType: 'TDM',
    mode: 'Squad',
    gunCategory: 'SMG',
    gun: 'UMP45',
    entryFee: 40,
    prizePool: 280,
    totalSlots: 8,
    filledSlots: 6,
    matchTime: 'Today, 6:00 PM',
    status: 'open',
    rules: 'UMP45 only. Fair play enforced.',
    roomId: 'SM77654',
    roomPassword: 'turbo1',
  },
  {
    id: 'c6',
    hostName: 'ShadowElite',
    hostId: 'p6',
    matchType: 'Classic',
    mode: 'Duo',
    map: 'Rondo',
    entryFee: 75,
    prizePool: 500,
    totalSlots: 8,
    filledSlots: 8,
    matchTime: 'Ongoing',
    status: 'ongoing',
    rules: 'Standard Rondo rules.',
    roomId: 'RN44321',
    roomPassword: 'shadow9',
  },
];

export const challengeService = {
  getChallenges(): Challenge[] {
    return MOCK_CHALLENGES;
  },

  getChallengesByType(type: string): Challenge[] {
    if (type === 'All') return MOCK_CHALLENGES;
    return MOCK_CHALLENGES.filter((c) => c.matchType === type);
  },

  getChallengeById(id: string): Challenge | undefined {
    return MOCK_CHALLENGES.find((c) => c.id === id);
  },
};
